## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]



In [4]:
# Create a list of at least 10 column names to use as X data
selected_columns = ['Education', 'Age', 'DistanceFromHome', 'JobSatisfaction', 'OverTime','StockOptionLevel','WorkLifeBalance','YearsAtCompany','YearsSinceLastPromotion','NumCompaniesWorked']



# Create X_df using your selected columns
X_df = attrition_df[selected_columns]


# Show the data types for X_df
X_df.dtypes



Education                   int64
Age                         int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
NumCompaniesWorked          int64
dtype: object

In [5]:
# Convert your X data to numeric data types however you see fit
#convert Overtime to an int64
X_df['OverTime'] = X_df['OverTime'].replace({'Yes': 1, 'No': 0})


C:\Users\14192\AppData\Local\Temp\ipykernel_3248\565398822.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X_df['OverTime'] = X_df['OverTime'].replace({'Yes': 1, 'No': 0})
C:\Users\14192\AppData\Local\Temp\ipykernel_3248\565398822.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_df['OverTime'] = X_df['OverTime'].replace({'Yes': 1, 'No': 0})


In [6]:
X_df['OverTime'].value_counts()

OverTime
0    1054
1     416
Name: count, dtype: int64

In [7]:
X_df.dtypes


Education                  int64
Age                        int64
DistanceFromHome           int64
JobSatisfaction            int64
OverTime                   int64
StockOptionLevel           int64
WorkLifeBalance            int64
YearsAtCompany             int64
YearsSinceLastPromotion    int64
NumCompaniesWorked         int64
dtype: object

In [8]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, random_state=42)



In [9]:
# Create a StandardScaler
scaler = StandardScaler()


# Fit the StandardScaler to the training data
X_scaler = scaler.fit(X_train)


# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)



In [10]:
# Create a OneHotEncoder for the Department column
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)


# Fit the encoder to the training data
encoder.fit_transform(y_train[['Department']])


# Create two new variables by applying the encoder
# to the training and testing data
y_dept_train_encoded = encoder.transform(y_train[['Department']])
y_dept_test_encoded = encoder.transform(y_test[['Department']])




In [11]:
y_dept_train_encoded

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
y_dept_test_encoded

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [13]:
# Create a OneHotEncoder for the Attrition column
encoder = OneHotEncoder(sparse_output=False, drop='first')


# Fit the encoder to the training data
encoder.fit_transform(y_train[['Attrition']])


# Create two new variables by applying the encoder
# to the training and testing data
y_att_train_encoded = encoder.transform(y_train[['Attrition']])
y_att_test_encoded = encoder.transform(y_test[['Attrition']])
y_att_train_encoded
y_att_test_encoded



array([[0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

## Create, Compile, and Train the Model

In [14]:
# Find the number of columns in the X training data
X_train.shape[1]


# Create the input layer
input_layer = layers.Input(shape=(X_train.shape[1],), name="input")


# Create at least two shared layers
shared1 = layers.Dense(units=64, activation='relu', name="shared1")(input_layer)
shared2 = layers.Dense(units=128, activation='relu', name="shared2")(shared1)


In [15]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
department_hidden = layers.Dense(units=32, activation='relu', name="department_hidden")(shared2)


# Create the output layer
department_output = layers.Dense(units=3, activation='softmax', name="department_output")(department_hidden)



In [16]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attrition_hidden = layers.Dense(units=32, activation='relu', name="attrition_hidden")(shared2)


# Create the output layer
attrition_output = layers.Dense(units=1, activation='sigmoid', name="attrition_output")(attrition_hidden)



In [17]:
print(y_dept_train_encoded[:5])  # Should display an array of one-hot encoded values
print(y_att_train_encoded[:5])  # Should display binary or one-hot encoded values


[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [18]:
# Create the model

model = Model(
    inputs=input_layer,
    outputs=[department_output, attrition_output]
)

# Compile the model
model.compile(
    optimizer='adam',
    loss={
        'department_output': 'categorical_crossentropy',  # Multi-class classification
        'attrition_output': 'binary_crossentropy'        # Binary classification
    },
    metrics={
        'department_output': 'accuracy',
        'attrition_output': 'accuracy'
    }
)



# Summarize the model
model.summary()


Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input (InputLayer)  │ (None, 10)        │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared1 (Dense)     │ (None, 64)        │        704 │ input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared2 (Dense)     │ (None, 128)       │      8,320 │ shared1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_hidden   │ (None, 32)        │      4,128 │ shared2[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_hidden    │ (None, 32)        │      4,128 │ shared2[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_output   │ (None, 3)         │         99 │ department_hidde… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_output    │ (None, 1)         │         33 │ attrition_hidden… │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 17,412 (68.02 KB)

 Trainable params: 17,412 (68.02 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
print(X_train_scaled.shape)


(1102, 10)


In [20]:
print(y_dept_train_encoded.shape)  # Should match `department_output` units
print(y_att_train_encoded.shape)  # Should be (samples, 1)


(1102, 3)
(1102, 1)


In [21]:
history = model.fit(
    {'input': X_train_scaled},  # Input dictionary with the name
    [y_dept_train_encoded, y_att_train_encoded],  # Outputs
    validation_data=(
        {'input': X_test_scaled},  # Validation input
        [y_dept_test_encoded, y_att_test_encoded]  # Validation outputs
    ),
    epochs=100,
    batch_size=32
)


Epoch 1/100


c:\Users\14192\Apps\anaconda3\envs\dev\lib\site-packages\keras\src\models\functional.py:238: UserWarning: The structure of `inputs` doesn't match the expected structure.
Expected: input
Received: inputs=['Tensor(shape=(None, 10))']
  warnings.warn(msg)


35/35 ━━━━━━━━━━━━━━━━━━━━ 5s 32ms/step - attrition_output_accuracy: 0.7791 - attrition_output_loss: 0.5724 - department_output_accuracy: 0.6273 - department_output_loss: 0.8946 - loss: 1.4670 - val_attrition_output_accuracy: 0.8696 - val_attrition_output_loss: 0.3896 - val_department_output_accuracy: 0.6522 - val_department_output_loss: 0.8152 - val_loss: 1.1936
Epoch 2/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - attrition_output_accuracy: 0.8508 - attrition_output_loss: 0.4040 - department_output_accuracy: 0.6571 - department_output_loss: 0.7583 - loss: 1.1625 - val_attrition_output_accuracy: 0.8723 - val_attrition_output_loss: 0.3702 - val_department_output_accuracy: 0.6522 - val_department_output_loss: 0.8132 - val_loss: 1.1751
Epoch 3/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8473 - attrition_output_loss: 0.3831 - department_output_accuracy: 0.6454 - department_output_loss: 0.7902 - loss: 1.1736 - val_attrition_output_accuracy: 0.8777 - val_attrit

In [23]:
# Evaluate the model with the testing data
model_loss, dept_loss, att_loss, dept_accuracy, att_accuracy = model.evaluate(
    {'input': X_test_scaled},
    [y_dept_test_encoded, y_att_test_encoded],
    verbose=2
)



12/12 - 0s - 8ms/step - attrition_output_accuracy: 0.8098 - attrition_output_loss: 1.2704 - department_output_accuracy: 0.5054 - department_output_loss: 2.6376 - loss: 3.8603


In [24]:
# Print the accuracy for both department and attrition
print(f"Department Accuracy: {dept_accuracy}")
print(f"Attrition Accuracy: {att_accuracy}")


Department Accuracy: 0.8097826242446899
Attrition Accuracy: 0.5054348111152649


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. I think accuracy was the best metric to use, because we are trying to predict on if a person will leave there job or not. 
2. For my output layers, for dept i used "softmax" since we are dealling with multiclass. For att, i used sigmoid because we are looking for a 1 or a 0 and sigmoid returns that, ie if over 0.5 then 1 and under 0.5 is 0.
3. I think the model could be improved by adding one or two more hidden layers. I also think that the features could be engineered more to be more contextual. I also think there was a few features that were not used that could maybe have helped the model. 